services:
  web:
    image: "docker.io/test3090/toy-store-web:latest"
    ports:
      - "5000:5000"
    volumes:
      - toy-store-vol:/usr/src/app-web
    # Add these environment variables for SonarScanner
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_SCANNER_HOME=/usr/src/sonar 
      - PATH=$PATH:/usr/src/sonar/bin
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins-vol
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080 

  sonarqube:
    image: sonarqube:latest
    depends_on:
      - sonarqube_db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  sonarqube_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Aa123456789?
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  toy-store-vol:    
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
  jenkins_home:
