services:
  web:
    image: "docker.io/test3090/toy-store:0.0.5"
    ports:
      - "5000:5000"
    volumes:
      - toy-store-vol:/usr/src/app-web
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 512m       
    mem_reservation: 128m 
    cpus: '0.5'
    environment:
    - SONAR_HOST_URL=http://sonarqube:9000
    - SONAR_PROJECT_KEY=Toy-Store
    
    depends_on:
      - sonarqube  
       
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network
    mem_limit: 1000m      
    mem_reservation: 128m
    cpus: '1'
  sonarqube:
    image: "sonarqube:latest"
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 1000m       
    mem_reservation: 128m 
    cpus: '2'

  jenkins:
    image: "jenkins/jenkins:latest"
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 1000m       
    mem_reservation: 128m 
    cpus: '1'

  sonarqube_db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Aa123456789?
      - POSTGRES_DB=sonar
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 512m
    mem_reservation: 128m 
    cpus: '0.5'

networks:
  app-network:
    driver: bridge   

volumes:
  jenkins_home:
  postgresql_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  toy-store-vol:
  sonarqube_db:
  mongo_data:
  