services:
  web:
    image: "docker.io/test3090/toy-store-web:latest"
    ports:
      - "5000:5000"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  sonarqube:
    image: "sonarqube:latest"
    ports:
      - "9000:9000"
  