services:
  web:
    image: "toy-store:0.10"
    ports:
      - "5000:5000"
    volumes:
      - toy-store-vol:/usr/src/app-web
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 512m       
    mem_reservation: 128m 
    cpus: '0.5'
    
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network
    mem_limit: 1000m      
    mem_reservation: 128m
    cpus: '1'
  
  jenkins:
    image: "jenkins/jenkins:latest"
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 1000m       
    mem_reservation: 128m 
    cpus: '1'

  Grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    mem_limit: 1000m       
    mem_reservation: 128m 
    cpus: '1'

  Promatheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - app-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    mem_limit: 1000m       
    mem_reservation: 128m 
    cpus: '1'

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 1000m       
    mem_reservation: 128m 
    cpus: '1'
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=:9100'
      - '--web.telemetry-path=/metrics'
      
  
networks:
  app-network:
    driver: bridge   

volumes:
  jenkins_home:
  toy-store-vol:
  mongo_data:
  grafana_data:
  prometheus_data:
  