services:
  web:
    build: .
    ports:
      - "5000:5000"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  sonarqube:
    image: "sonarqube:latest"
    ports:
      - "9000:9000"
  