apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Adjust storage size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1 # Single instance of Jenkins for now; scale as needed.
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins-container
          image: jenkins/jenkins:lts # Use the latest LTS version of Jenkins.
          ports:
            - containerPort: 8080 # Jenkins UI port.
            - containerPort: 50000 # Jenkins agent communication port.
          resources:
            requests:
              memory: "512Mi" # Minimum memory request.
              cpu: "500m"     # Minimum CPU request.
            limits:
              memory: "2Gi"   # Maximum memory limit.
              cpu: "2"        # Maximum CPU limit.
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home # Default Jenkins data directory.
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - name: jenkins-ui
      port: 8080 # External port for Jenkins UI
      targetPort: 8080 # Internal port for Jenkins UI
    - name: jenkins-agent
      port: 50000 # Jenkins agent port
      targetPort: 5050
  selector:
    app: jenkins
