auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  
common:
  ring:
    kvstore:
      store: "inmemory" 
    replication_factor: 1
    instance_addr: 0.0.0.0
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1

schema_config:
  configs:
    - from: "2020-10-24"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: "index_"
        period: "24h"

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-index/
    cache_location: /tmp/loki/tsdb-cache/
